/**
 * MIE_Bridge — Hardware Abstraction Layer for MokyaInput Engine
 *
 * Phase 1–3: delegates to MIE_Processor (JS implementation)
 * Phase 4:   replaces _jsImpl with mie_core.wasm compiled from
 *            firmware/mie sources via Emscripten (build_wasm.sh).
 *
 * WASM module (standalone, no Emscripten JS glue):
 *   Exports: mie_load_zh_dict, mie_load_en_dict, mie_ctx_init,
 *            mie_key, mie_pop_commit, mie_input_ptr, mie_mode_ptr,
 *            mie_cand_count, mie_cand_word_ptr, mie_sel,
 *            mie_page_sz, mie_page_cnt, mie_clear_state,
 *            malloc, free, memory
 *   Required env import:
 *            emscripten_notify_memory_growth (no-op is fine)
 *
 * Dictionary format: MIED v2 binary (two files: dict_dat.bin + dict_values.bin)
 * Generated by: mokya-twin/tools/mock_to_mied.py  (mock data)
 *               firmware/mie/tools/gen_dict.py      (full libchewing data)
 */

import { MIE_Processor, InputMode } from '../core/mie-processor.js';
import { MIE_Trie }                 from '../core/mie-trie.js';
import { MIE_Timer }                from '../core/mie-timer.js';

export class MIE_Bridge extends EventTarget {
  constructor() {
    super();

    // ── JS-side implementation (Phase 1–3) ──────────────────────
    this._trie   = new MIE_Trie();
    this._timer  = new MIE_Timer();
    this._jsImpl = new MIE_Processor(this._trie, this._timer);

    // ── WASM slot (Phase 4) ──────────────────────────────────────
    /** @type {WebAssembly.Instance|null} */
    this._wasm    = null;
    this._useWasm = false;

    /** TextDecoder for reading UTF-8 strings from WASM linear memory */
    this._dec = new TextDecoder();

    /** Accumulated committed text (WASM mode); cleared on action:enter */
    this._pendingCommitted = '';

    // Forward JS processor events to bridge consumers
    this._forwardEvents();

    this._dictionaryLoaded = false;
  }

  // ── Dictionary loading ───────────────────────────────────────

  /**
   * Load the phonetic dictionary.
   *
   * WASM mode: pass two binary URLs (MIED v2 dat + val files).
   *   await bridge.loadDictionary('data/dict_dat.bin', 'data/dict_values.bin')
   *
   * JS mode: pass a single JSON URL (legacy zhuyin-mock.json).
   *   await bridge.loadDictionary('data/zhuyin-mock.json')
   *
   * @param {string} zhDatOrJson  URL for dict_dat.bin (WASM) or .json (JS)
   * @param {string} [zhVal]      URL for dict_values.bin (WASM only)
   * @param {string} [enDat]      URL for en_dat.bin     (optional English dict)
   * @param {string} [enVal]      URL for en_values.bin  (optional English dict)
   */
  async loadDictionary(zhDatOrJson, zhVal, enDat, enVal) {
    if (this._useWasm && this._wasm) {
      await this._wasmLoadDict(zhDatOrJson, zhVal, enDat, enVal);
    } else {
      // JS fallback: load JSON trie
      const url = zhDatOrJson;
      let data;
      if (typeof url === 'string') {
        const res = await fetch(url);
        data = await res.json();
      } else {
        data = url;
      }
      this._trie.loadFromJson(data);
      this._dictionaryLoaded = true;
      console.log('[MIE_Bridge] JSON dictionary loaded:', this._trie.nodeCount, 'nodes');
      this._emit('bridge:ready', { nodeCount: this._trie.nodeCount });
    }
  }

  // ── WASM loading (Phase 4 entry point) ──────────────────────

  /**
   * Load mie_core.wasm. Falls back to JS implementation silently on failure.
   * Call BEFORE loadDictionary() so WASM dict loading is used.
   * @param {string} wasmPath  path to mie_core.wasm
   */
  async loadWasm(wasmPath) {
    try {
      const response = await fetch(wasmPath);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const buffer = await response.arrayBuffer();

      const imports = {
        // Standalone WASM only needs this one env import
        env: {
          emscripten_notify_memory_growth: () => {},
        },
        wasi_snapshot_preview1: {},
      };

      const { instance } = await WebAssembly.instantiate(buffer, imports);
      this._wasm = instance.exports;
      this._wasm._initialize();
      this._useWasm = true;
      console.log('[MIE_Bridge] WASM module loaded — mie_core active');
      this._emit('bridge:wasm_loaded', {});
    } catch (err) {
      console.info('[MIE_Bridge] WASM unavailable, using JS impl:', err.message);
      this._useWasm = false;
    }
  }

  // ── Public API (stable across Phase 1–4) ────────────────────

  /**
   * Process a key tap event.
   * @param {{ key: {row:number, col:number}, tapCount: number }} keyEvent
   */
  processKeyTap(keyEvent) {
    if (this._useWasm && this._wasm) {
      const { row, col } = keyEvent.key;
      // Capture input string before the key so we can detect OK-with-empty-input
      const inputBefore = this._readWasmStr(this._wasm.mie_input_ptr());
      this._wasm.mie_key(row, col, 1);
      this._wasm.mie_key(row, col, 0);
      this._pollWasmState();
      // OK key (5,4) with no pending composition → emit action:enter to send message
      if (row === 5 && col === 4 && inputBefore === '') {
        this._emit('action:enter', { text: this._pendingCommitted });
        this._pendingCommitted = '';
      }
    } else {
      this._jsImpl.processKeyTap(keyEvent);
    }
  }

  /**
   * Process immediate key-down (for navigation feedback).
   * @param {{ key: {row:number, col:number} }} keyEvent
   */
  processKeyDown(keyEvent) {
    if (this._useWasm && this._wasm) {
      this._wasm.mie_key(keyEvent.key.row, keyEvent.key.col, 1);
      this._pollWasmState();
    } else {
      this._jsImpl.processKeyDown(keyEvent);
    }
  }

  /** Get current input display string. */
  getInputStr() {
    if (this._useWasm && this._wasm) {
      return this._readWasmStr(this._wasm.mie_input_ptr());
    }
    return this._jsImpl.inputText ?? '';
  }

  /** Get current mode indicator ("中"/"EN"/"ABC"/"abc"/"ㄅ"). */
  getModeStr() {
    if (this._useWasm && this._wasm) {
      return this._readWasmStr(this._wasm.mie_mode_ptr());
    }
    return this._jsImpl.mode ?? '';
  }

  /** Get current composition buffer as string array (JS mode only). */
  getCompositionBuffer() {
    if (this._useWasm) return [];
    return [...this._jsImpl.compBuffer];
  }

  /** Get current candidate list. */
  getCandidates() {
    if (this._useWasm && this._wasm) {
      const n = this._wasm.mie_cand_count();
      const out = [];
      for (let i = 0; i < n; i++) {
        out.push(this._readWasmStr(this._wasm.mie_cand_word_ptr(i)));
      }
      return out;
    }
    return [...this._jsImpl.candidates];
  }

  /** Get selected candidate index on the current page. */
  getPageSel() {
    if (this._useWasm && this._wasm) return this._wasm.mie_sel();
    return 0;
  }

  /** Get page size. */
  getPageSize() {
    if (this._useWasm && this._wasm) return this._wasm.mie_page_sz();
    return 5;
  }

  /** Get total page count. */
  getPageCount() {
    if (this._useWasm && this._wasm) return this._wasm.mie_page_cnt();
    return 0;
  }

  /**
   * Select a candidate by index and commit.
   * @param {number} idx
   */
  selectCandidate(idx) {
    if (this._useWasm && this._wasm) {
      // Navigate to the desired candidate using DOWN keys, then confirm with OK.
      const cur = this._wasm.mie_sel();
      const pageSize = this._wasm.mie_page_sz();
      const steps = ((idx % pageSize) - cur + pageSize) % pageSize;
      for (let i = 0; i < steps; i++) {
        this._wasm.mie_key(5, 1, 1); // DOWN
        this._wasm.mie_key(5, 1, 0);
      }
      this._wasm.mie_key(5, 4, 1); // OK
      this._wasm.mie_key(5, 4, 0);
      this._pollWasmState();
    } else {
      this._jsImpl.selectCandidateAt(idx);
    }
  }

  /** Reset composition state. */
  reset() {
    if (this._useWasm && this._wasm) {
      this._wasm.mie_clear_state();
    } else {
      this._jsImpl._resetComposition();
    }
  }

  /** Cycle through input modes (JS mode only; WASM uses MODE key). */
  cycleMode() {
    if (!this._useWasm) this._jsImpl._cycleMode();
  }

  get currentMode()    { return this._useWasm ? this.getModeStr() : this._jsImpl.mode; }
  get inputText()      { return this._useWasm ? this.getInputStr() : this._jsImpl.inputText; }
  get isWasmActive()   { return this._useWasm; }
  get isDictLoaded()   { return this._dictionaryLoaded; }

  // ── WASM internals ───────────────────────────────────────────

  /**
   * Load MIED binary dictionaries into WASM linear memory.
   */
  async _wasmLoadDict(zhDatUrl, zhValUrl, enDatUrl, enValUrl) {
    const wasm = this._wasm;
    const mem  = wasm.memory;

    const [zhDat, zhVal] = await Promise.all([
      fetch(zhDatUrl).then(r => r.arrayBuffer()),
      fetch(zhValUrl).then(r => r.arrayBuffer()),
    ]);

    const zhDatPtr = this._wasmAlloc(new Uint8Array(zhDat));
    const zhValPtr = this._wasmAlloc(new Uint8Array(zhVal));

    const ok = wasm.mie_load_zh_dict(zhDatPtr, zhDat.byteLength, zhValPtr, zhVal.byteLength);
    wasm.free(zhDatPtr);
    wasm.free(zhValPtr);

    if (!ok) throw new Error('mie_load_zh_dict failed — invalid MIED binary?');

    // Optional English dictionary
    if (enDatUrl && enValUrl) {
      const [enDat, enVal] = await Promise.all([
        fetch(enDatUrl).then(r => r.arrayBuffer()),
        fetch(enValUrl).then(r => r.arrayBuffer()),
      ]);
      const enDatPtr = this._wasmAlloc(new Uint8Array(enDat));
      const enValPtr = this._wasmAlloc(new Uint8Array(enVal));
      wasm.mie_load_en_dict(enDatPtr, enDat.byteLength, enValPtr, enVal.byteLength);
      wasm.free(enDatPtr);
      wasm.free(enValPtr);
    }

    const ctxOk = wasm.mie_ctx_init();
    if (!ctxOk) throw new Error('mie_ctx_init failed');

    this._dictionaryLoaded = true;
    console.log('[MIE_Bridge] WASM dict loaded — mie_ctx ready');
    this._emit('bridge:ready', { wasm: true });
  }

  /**
   * Copy a Uint8Array into WASM heap and return its pointer.
   * Caller must wasm.free() the pointer when done.
   */
  _wasmAlloc(data) {
    const ptr = this._wasm.malloc(data.length);
    new Uint8Array(this._wasm.memory.buffer, ptr, data.length).set(data);
    return ptr;
  }

  /**
   * Read a null-terminated UTF-8 string from WASM linear memory.
   */
  _readWasmStr(ptr) {
    if (!ptr) return '';
    const heap = new Uint8Array(this._wasm.memory.buffer);
    let end = ptr;
    while (heap[end]) end++;
    return this._dec.decode(heap.subarray(ptr, end));
  }

  /**
   * Poll WASM state after a key event and dispatch JS-compatible events.
   * Reads committed text (if any) and fires composition:update / composition:commit.
   */
  _pollWasmState() {
    const wasm = this._wasm;

    // Drain committed text into _pendingCommitted and fire composition:commit
    const commitPtr = wasm.malloc(256);
    const n = wasm.mie_pop_commit(commitPtr, 256);
    if (n > 0) {
      const text = this._readWasmStr(commitPtr);
      wasm.free(commitPtr);
      this._pendingCommitted = (this._pendingCommitted ?? '') + text;
      this.dispatchEvent(new CustomEvent('composition:commit', { detail: { text } }));
    } else {
      wasm.free(commitPtr);
    }

    // Emit composition update
    const candidates = this.getCandidates();
    const inputStr   = this.getInputStr();
    const modeStr    = this.getModeStr();
    this.dispatchEvent(new CustomEvent('composition:update', {
      detail: {
        buffer:     inputStr,
        candidates,
        committed:  this._pendingCommitted ?? '',
        mode:       modeStr,
        sel:        this.getPageSel(),
        pageCount:  this.getPageCount(),
        wasm:       true,
      }
    }));
  }

  // ── JS event forwarding (Phase 1–3) ─────────────────────────

  _forwardEvents() {
    const forward = (type) => {
      this._jsImpl.addEventListener(type, (e) => {
        this.dispatchEvent(new CustomEvent(type, { detail: e.detail }));
      });
    };
    ['composition:update','composition:commit','cursor:move',
     'action:back','action:menu','action:enter','action:delete',
     'mode:change'
    ].forEach(forward);
  }

  _emit(type, detail) {
    this.dispatchEvent(new CustomEvent(type, { detail }));
  }
}
