/**
 * MIE_Bridge — Hardware Abstraction Layer for MokyaInput Engine
 *
 * Phase 1–3: delegates to MIE_Processor (JS implementation)
 * Phase 4:   replaces _jsImpl with mie_core.wasm compiled from
 *            firmware/mie sources (v2 listener API) via Emscripten.
 *
 * WASM module (standalone, no Emscripten JS glue):
 *   Exports: mie_load_zh_dict, mie_load_en_dict, mie_load_v4_dict,
 *            mie_ctx_init,
 *            mie_key(keycode, pressed, now_ms),
 *            mie_tick(now_ms),
 *            mie_pop_commit, mie_pop_delete_before, mie_pop_cursor_move,
 *            mie_input_ptr, mie_mode_ptr,
 *            mie_cand_count, mie_cand_word_ptr, mie_sel,
 *            mie_page_sz, mie_page_cnt, mie_cur_page,
 *            mie_page_cand_ptr, mie_page_cand_cnt,
 *            mie_picker_active, mie_picker_cols, mie_picker_cell_count,
 *            mie_picker_cell_ptr, mie_picker_selected,
 *            mie_lru_serialized_size, mie_lru_count,
 *            mie_serialize_lru, mie_load_lru,
 *            mie_clear_state, mie_set_text_context,
 *            malloc, free, memory
 *   Required env import:
 *            emscripten_notify_memory_growth (no-op is fine)
 *
 * Dictionary format: MIED v2 binary (dict_dat.bin + dict_values.bin) and
 *                    MIE4 v4 composition blob (dict_v4.bin, single file).
 * Generated by: firmware/mie/tools/gen_dict.py (v4 via --v4-output)
 */

import { MIE_Processor, InputMode } from '../core/mie-processor.js';
import { MIE_Trie }                 from '../core/mie-trie.js';
import { MIE_Timer }                from '../core/mie-timer.js';
import { KEYCODE }                  from './keyboard-hal.js';

export class MIE_Bridge extends EventTarget {
  constructor() {
    super();

    // ── JS-side implementation (Phase 1–3 fallback) ──────────────
    this._trie   = new MIE_Trie();
    this._timer  = new MIE_Timer();
    this._jsImpl = new MIE_Processor(this._trie, this._timer);

    // ── WASM slot (Phase 4) ──────────────────────────────────────
    /** @type {WebAssembly.Instance|null} */
    this._wasm    = null;
    this._useWasm = false;

    /** TextDecoder for reading UTF-8 strings from WASM linear memory */
    this._dec = new TextDecoder();

    /** Accumulated committed text (WASM mode); cleared on action:enter */
    this._pendingCommitted = '';

    /** setInterval handle driving mie_tick() */
    this._tickTimer = null;

    /** Input pending state captured at press-edge, read at release-edge so
     *  OK-with-empty-composition can fire action:enter. */
    this._inputBeforePress = '';

    /** LRU persistence: debounced save handle and storage key. */
    this._lruSaveTimer = null;
    this._lruStorageKey = 'mie.lru.v1';

    // Forward JS processor events to bridge consumers
    this._forwardEvents();

    this._dictionaryLoaded = false;
  }

  // ── Dictionary loading ───────────────────────────────────────

  /**
   * Load the phonetic dictionary.
   *
   * WASM mode: pass two MIED v2 URLs plus optional en + v4 blobs.
   *   await bridge.loadDictionary('data/dict_dat.bin', 'data/dict_values.bin',
   *                               'data/en_dat.bin',    'data/en_values.bin',
   *                               'data/dict_v4.bin')
   *
   * JS mode: pass a single JSON URL (legacy zhuyin-mock.json).
   *   await bridge.loadDictionary('data/zhuyin-mock.json')
   *
   * @param {string} zhDatOrJson  URL for dict_dat.bin (WASM) or .json (JS)
   * @param {string} [zhVal]      URL for dict_values.bin (WASM only)
   * @param {string} [enDat]      URL for en_dat.bin     (optional English dict)
   * @param {string} [enVal]      URL for en_values.bin  (optional English dict)
   * @param {string} [v4Url]      URL for dict_v4.bin (MIE4 composition + embedded SmartEn)
   */
  async loadDictionary(zhDatOrJson, zhVal, enDat, enVal, v4Url) {
    if (this._useWasm && this._wasm) {
      await this._wasmLoadDict(zhDatOrJson, zhVal, enDat, enVal, v4Url);
    } else {
      // JS fallback: load JSON trie
      const url = zhDatOrJson;
      let data;
      if (typeof url === 'string') {
        const res = await fetch(url);
        data = await res.json();
      } else {
        data = url;
      }
      this._trie.loadFromJson(data);
      this._dictionaryLoaded = true;
      console.log('[MIE_Bridge] JSON dictionary loaded:', this._trie.nodeCount, 'nodes');
      this._emit('bridge:ready', { nodeCount: this._trie.nodeCount });
    }
  }

  // ── WASM loading (Phase 4 entry point) ──────────────────────

  /**
   * Load mie_core.wasm. Falls back to JS implementation silently on failure.
   * Call BEFORE loadDictionary() so WASM dict loading is used.
   * @param {string} wasmPath  path to mie_core.wasm
   */
  async loadWasm(wasmPath) {
    try {
      const response = await fetch(wasmPath);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const buffer = await response.arrayBuffer();

      const imports = {
        // Standalone WASM only needs this one env import
        env: {
          emscripten_notify_memory_growth: () => {},
        },
        wasi_snapshot_preview1: {},
      };

      const { instance } = await WebAssembly.instantiate(buffer, imports);
      this._wasm = instance.exports;
      this._wasm._initialize();
      this._useWasm = true;
      console.log('[MIE_Bridge] WASM module loaded — mie_core active');
      this._emit('bridge:wasm_loaded', {});
    } catch (err) {
      console.info('[MIE_Bridge] WASM unavailable, using JS impl:', err.message);
      this._useWasm = false;
    }
  }

  // ── Public API (stable across Phase 1–4) ────────────────────

  /**
   * Process key-down (press edge). Fires once per physical press.
   * KeyboardHAL emits key:down on keydown and key:tap on keyup, so we
   * map them to the two ImeLogic edges: press here, release in
   * processKeyTap. Doing both edges in processKeyTap AND another press
   * in processKeyDown would double-trigger every input.
   *
   * keyEvent.key.keycode is the canonical firmware MOKYA_KEY_* value
   * (set by keyboard-hal.js); USB Control / serial injection paths can
   * synthesise events with the same keycode field and reuse this entry.
   *
   * @param {{ key: { keycode: number } }} keyEvent
   */
  processKeyDown(keyEvent) {
    if (this._useWasm && this._wasm) {
      const keycode = keyEvent.key.keycode;
      // Capture pending buffer before the press so the release edge can
      // detect OK-with-empty-composition.
      this._inputBeforePress = this._readWasmStr(this._wasm.mie_input_ptr());
      this._wasm.mie_key(keycode, 1, this._now());
      this._pollWasmState();
    } else {
      this._jsImpl.processKeyDown(keyEvent);
    }
  }

  /**
   * Process key-up (release edge).
   * @param {{ key: { keycode: number }, tapCount: number }} keyEvent
   */
  processKeyTap(keyEvent) {
    if (this._useWasm && this._wasm) {
      const keycode = keyEvent.key.keycode;
      this._wasm.mie_key(keycode, 0, this._now());
      this._pollWasmState();
      // OK with no pending composition → send accumulated committed text.
      if (keycode === KEYCODE.OK && this._inputBeforePress === '') {
        this._emit('action:enter', { text: this._pendingCommitted });
        this._pendingCommitted = '';
        // Resync firmware: next message starts a fresh sentence (cap first
        // word, no leading space).
        this.setTextContext('');
      }
      this._inputBeforePress = '';
    } else {
      this._jsImpl.processKeyTap(keyEvent);
    }
  }

  /** Get current input display string. */
  getInputStr() {
    if (this._useWasm && this._wasm) {
      return this._readWasmStr(this._wasm.mie_input_ptr());
    }
    return this._jsImpl.inputText ?? '';
  }

  /** Get current mode indicator: "中" (SmartZh), "EN" (SmartEn), or "ABC" (Direct). */
  getModeStr() {
    if (this._useWasm && this._wasm) {
      return this._readWasmStr(this._wasm.mie_mode_ptr());
    }
    return this._jsImpl.mode ?? '';
  }

  /**
   * Single-snapshot pending view matching mie::PendingView. Style values:
   *   0 = None, 1 = PrefixBold, 2 = Inverted.
   * matchedPrefixBytes counts UTF-8 bytes (not codepoints) of the matched
   * prefix inside `str`; it is 0 when style !== PrefixBold.
   */
  getPendingView() {
    if (this._useWasm && this._wasm) {
      const str = this._readWasmStr(this._wasm.mie_input_ptr());
      return {
        str,
        byteLen:            this._wasm.mie_pending_byte_len(),
        matchedPrefixBytes: this._wasm.mie_pending_matched_prefix(),
        style:              this._wasm.mie_pending_style(),
      };
    }
    // JS fallback: flat text, no style info
    const str = this._jsImpl.inputText ?? '';
    return { str, byteLen: new TextEncoder().encode(str).length, matchedPrefixBytes: 0, style: str ? 1 : 0 };
  }

  /** Get current composition buffer as string array (JS mode only). */
  getCompositionBuffer() {
    if (this._useWasm) return [];
    return [...this._jsImpl.compBuffer];
  }

  /** Get candidates on the current page (updates after TAB / UP / DOWN). */
  getCandidates() {
    if (this._useWasm && this._wasm) {
      const n = this._wasm.mie_page_cand_cnt();
      const out = [];
      for (let i = 0; i < n; i++) {
        out.push(this._readWasmStr(this._wasm.mie_page_cand_ptr(i)));
      }
      return out;
    }
    return [...this._jsImpl.candidates];
  }

  /** Get the full merged candidate list (across all firmware pages). */
  getAllCandidates() {
    if (this._useWasm && this._wasm) {
      const n = this._wasm.mie_cand_count();
      const out = [];
      for (let i = 0; i < n; i++) {
        out.push(this._readWasmStr(this._wasm.mie_cand_word_ptr(i)));
      }
      return out;
    }
    return [...this._jsImpl.candidates];
  }

  /** Absolute selected index over the full merged candidate list. */
  getSelectedAbs() {
    if (this._useWasm && this._wasm) return this._wasm.mie_selected_abs();
    return 0;
  }

  /** Get selected candidate index on the current page. */
  getPageSel() {
    if (this._useWasm && this._wasm) return this._wasm.mie_sel();
    return 0;
  }

  /** Get page size. */
  getPageSize() {
    if (this._useWasm && this._wasm) return this._wasm.mie_page_sz();
    return 5;
  }

  /** Get total page count. */
  getPageCount() {
    if (this._useWasm && this._wasm) return this._wasm.mie_page_cnt();
    return 0;
  }

  /** Get current page index (0-based). */
  getCurrentPage() {
    if (this._useWasm && this._wasm) return this._wasm.mie_cur_page();
    return 0;
  }

  /**
   * Select a candidate by index and commit.
   * @param {number} idx
   */
  selectCandidate(idx) {
    if (this._useWasm && this._wasm) {
      // Navigate to the desired candidate using RIGHT keys (v2 candidate nav),
      // then confirm with OK.
      const cur = this._wasm.mie_sel();
      const pageSize = this._wasm.mie_page_sz();
      const steps = ((idx % pageSize) - cur + pageSize) % pageSize;
      for (let i = 0; i < steps; i++) {
        this._wasm.mie_key(KEYCODE.RIGHT, 1, this._now());
        this._wasm.mie_key(KEYCODE.RIGHT, 0, this._now());
      }
      this._wasm.mie_key(KEYCODE.OK, 1, this._now());
      this._wasm.mie_key(KEYCODE.OK, 0, this._now());
      this._pollWasmState();
    } else {
      this._jsImpl.selectCandidateAt(idx);
    }
  }

  /** Reset composition state. */
  reset() {
    if (this._useWasm && this._wasm) {
      this._wasm.mie_clear_state();
    } else {
      this._jsImpl._resetComposition();
    }
  }

  /**
   * Snapshot of the SYM1 long-press symbol picker overlay.
   * Returns `{ active: false, cells: [] }` in JS fallback mode.
   * @returns {{ active: boolean, cols: number, cellCount: number, selected: number, cells: string[] }}
   */
  getPicker() {
    if (!this._useWasm || !this._wasm) {
      return { active: false, cols: 0, cellCount: 0, selected: 0, cells: [] };
    }
    const active = this._wasm.mie_picker_active() !== 0;
    if (!active) {
      return { active: false, cols: 0, cellCount: 0, selected: 0, cells: [] };
    }
    const cols      = this._wasm.mie_picker_cols();
    const cellCount = this._wasm.mie_picker_cell_count();
    const selected  = this._wasm.mie_picker_selected();
    const cells     = [];
    for (let i = 0; i < cellCount; i++) {
      cells.push(this._readWasmStr(this._wasm.mie_picker_cell_ptr(i)));
    }
    return { active, cols, cellCount, selected, cells };
  }

  /**
   * Sync the firmware's SmartEn sentence-aware state with the host text.
   * Pass the last 1–2 codepoints immediately before the cursor (or '' to
   * mark a fresh sentence). Firmware uses this to decide whether the
   * next commit gets a leading space and whether it should be capitalised.
   *
   * Call after any external edit to the committed buffer — message sent,
   * DEL that pops a char, paste, cursor moves — so firmware's tracked
   * state matches reality.
   */
  setTextContext(prevUtf8) {
    if (!this._useWasm || !this._wasm) return;
    const enc = new TextEncoder();
    const bytes = enc.encode(prevUtf8 ?? '');
    const ptr = this._wasm.malloc(bytes.length + 1);
    new Uint8Array(this._wasm.memory.buffer, ptr, bytes.length).set(bytes);
    new Uint8Array(this._wasm.memory.buffer, ptr + bytes.length, 1)[0] = 0;
    this._wasm.mie_set_text_context(ptr);
    this._wasm.free(ptr);
  }

  /**
   * Return the last `n` codepoints (default 2) of `s` as a UTF-16 string.
   * Walks codepoints — safe for surrogate pairs (emoji) and CJK.
   */
  static lastCodepoints(s, n = 2) {
    if (!s) return '';
    const cps = Array.from(s);
    return cps.slice(-n).join('');
  }

  /** Cycle through input modes (JS mode only; WASM uses MODE key). */
  cycleMode() {
    if (!this._useWasm) this._jsImpl._cycleMode();
  }

  /** Flush the debounced LRU save immediately (e.g. from `beforeunload`). */
  flushLru() {
    if (this._lruSaveTimer != null) {
      clearTimeout(this._lruSaveTimer);
      this._lruSaveTimer = null;
    }
    this._saveLruNow();
  }

  get currentMode()    { return this._useWasm ? this.getModeStr() : this._jsImpl.mode; }
  get inputText()      { return this._useWasm ? this.getInputStr() : this._jsImpl.inputText; }
  get isWasmActive()   { return this._useWasm; }
  get isDictLoaded()   { return this._dictionaryLoaded; }

  // ── WASM internals ───────────────────────────────────────────

  /** Monotonic millisecond clock used as KeyEvent::now_ms. */
  _now() {
    return performance.now() | 0;
  }

  /**
   * Load MIED binary dictionaries into WASM linear memory.
   */
  async _wasmLoadDict(zhDatUrl, zhValUrl, enDatUrl, enValUrl, v4Url) {
    const wasm = this._wasm;

    const [zhDat, zhVal] = await Promise.all([
      fetch(zhDatUrl).then(r => r.arrayBuffer()),
      fetch(zhValUrl).then(r => r.arrayBuffer()),
    ]);

    const zhDatPtr = this._wasmAlloc(new Uint8Array(zhDat));
    const zhValPtr = this._wasmAlloc(new Uint8Array(zhVal));

    const ok = wasm.mie_load_zh_dict(zhDatPtr, zhDat.byteLength, zhValPtr, zhVal.byteLength);
    // Keep dict buffers alive: TrieSearcher::load_from_memory stores the
    // pointers by reference, so we must NOT free them here.

    if (!ok) {
      wasm.free(zhDatPtr);
      wasm.free(zhValPtr);
      throw new Error('mie_load_zh_dict failed — invalid MIED binary?');
    }

    // Optional English dictionary
    if (enDatUrl && enValUrl) {
      const [enDat, enVal] = await Promise.all([
        fetch(enDatUrl).then(r => r.arrayBuffer()),
        fetch(enValUrl).then(r => r.arrayBuffer()),
      ]);
      const enDatPtr = this._wasmAlloc(new Uint8Array(enDat));
      const enValPtr = this._wasmAlloc(new Uint8Array(enVal));
      wasm.mie_load_en_dict(enDatPtr, enDat.byteLength, enValPtr, enVal.byteLength);
    }

    // Optional MIE4 v4 composition dict (single blob, embedded SmartEn).
    // Must be loaded before mie_ctx_init so attach_composition_searcher
    // runs inside the constructor path; if loaded later, glue re-attaches.
    if (v4Url) {
      const v4 = await fetch(v4Url).then(r => r.arrayBuffer());
      const v4Ptr = this._wasmAlloc(new Uint8Array(v4));
      const v4Ok = wasm.mie_load_v4_dict(v4Ptr, v4.byteLength);
      if (!v4Ok) {
        wasm.free(v4Ptr);
        console.warn('[MIE_Bridge] mie_load_v4_dict failed — continuing without v4');
      }
      // Keep v4 buffer alive like the v2 dicts.
    }

    const ctxOk = wasm.mie_ctx_init();
    if (!ctxOk) throw new Error('mie_ctx_init failed');

    // Start the tick loop (drives multi-tap auto-commit and SYM1 long-press).
    this._startTickLoop();

    this._loadLru();

    this._dictionaryLoaded = true;
    console.log('[MIE_Bridge] WASM dict loaded — mie_ctx ready');
    this._emit('bridge:ready', { wasm: true });
  }

  /**
   * Debounced serialise of the firmware's LruCache into localStorage.
   * Coalesces bursts (a typed word fires several commits) into a single
   * write. Silently no-ops in JS fallback mode or if storage is unavailable
   * (Safari private mode, quota exceeded, etc.).
   */
  _saveLru() {
    if (!this._useWasm || !this._wasm) return;
    if (this._lruSaveTimer != null) return;
    this._lruSaveTimer = setTimeout(() => {
      this._lruSaveTimer = null;
      this._saveLruNow();
    }, 2000);
  }

  _saveLruNow() {
    if (!this._useWasm || !this._wasm) return;
    const wasm = this._wasm;
    const cap = wasm.mie_lru_serialized_size();
    if (cap <= 0) return;
    const ptr = wasm.malloc(cap);
    try {
      const n = wasm.mie_serialize_lru(ptr, cap);
      if (n <= 0) return;
      const bytes = new Uint8Array(wasm.memory.buffer, ptr, n).slice();
      let bin = '';
      for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
      window.localStorage?.setItem(this._lruStorageKey, btoa(bin));
    } catch (err) {
      console.warn('[MIE_Bridge] LRU save failed:', err.message);
    } finally {
      wasm.free(ptr);
    }
  }

  _loadLru() {
    if (!this._useWasm || !this._wasm) return;
    let b64;
    try {
      b64 = window.localStorage?.getItem(this._lruStorageKey);
    } catch (_) {
      return;
    }
    if (!b64) return;
    const wasm = this._wasm;
    let bin;
    try {
      bin = atob(b64);
    } catch (_) {
      window.localStorage?.removeItem(this._lruStorageKey);
      return;
    }
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    const ptr = wasm.malloc(bytes.length);
    try {
      new Uint8Array(wasm.memory.buffer, ptr, bytes.length).set(bytes);
      const ok = wasm.mie_load_lru(ptr, bytes.length);
      if (!ok) {
        window.localStorage?.removeItem(this._lruStorageKey);
        console.info('[MIE_Bridge] LRU snapshot rejected (format mismatch); cleared.');
      }
    } finally {
      wasm.free(ptr);
    }
  }

  /**
   * Copy a Uint8Array into WASM heap and return its pointer.
   * Caller must wasm.free() the pointer when done (except for dict data,
   * which must remain alive for the lifetime of the context).
   */
  _wasmAlloc(data) {
    const ptr = this._wasm.malloc(data.length);
    new Uint8Array(this._wasm.memory.buffer, ptr, data.length).set(data);
    return ptr;
  }

  /**
   * Read a null-terminated UTF-8 string from WASM linear memory.
   */
  _readWasmStr(ptr) {
    if (!ptr) return '';
    const heap = new Uint8Array(this._wasm.memory.buffer);
    let end = ptr;
    while (heap[end]) end++;
    return this._dec.decode(heap.subarray(ptr, end));
  }

  /** Drive ImeLogic::tick() at ~20 ms cadence (multi-tap / long-press). */
  _startTickLoop() {
    if (this._tickTimer != null) return;
    this._tickTimer = setInterval(() => {
      if (!this._useWasm || !this._wasm) return;
      const changed = this._wasm.mie_tick(this._now());
      if (changed) this._pollWasmState();
    }, 20);
  }

  /**
   * Poll WASM state after a key/tick event and dispatch JS-compatible events.
   * Drains listener signals (commit text, delete_before, cursor_move) and
   * fires composition:update / composition:commit / action:delete / cursor:move.
   */
  _pollWasmState() {
    const wasm = this._wasm;

    // Drain committed text
    const commitPtr = wasm.malloc(512);
    const n = wasm.mie_pop_commit(commitPtr, 512);
    let committedNow = '';
    if (n > 0) {
      committedNow = this._readWasmStr(commitPtr);
      this._pendingCommitted = (this._pendingCommitted ?? '') + committedNow;
      this.dispatchEvent(new CustomEvent('composition:commit', { detail: { text: committedNow } }));
      // Firmware's LruCache mutates on SmartZh candidate commits — schedule
      // a debounced save so personalisation survives reloads.
      this._saveLru();
    }
    wasm.free(commitPtr);

    // Drain delete-before signal (DEL pressed with no pending composition)
    if (wasm.mie_pop_delete_before()) {
      // UI convention: action:delete pops the last char from the committed buffer
      if (this._pendingCommitted && this._pendingCommitted.length > 0) {
        // Pop the last full codepoint to stay UTF-16-safe
        this._pendingCommitted = Array.from(this._pendingCommitted).slice(0, -1).join('');
      }
      // Resync firmware's SmartEn state with the new trailing chars so
      // auto-cap / leading-space decisions match reality.
      this.setTextContext(MIE_Bridge.lastCodepoints(this._pendingCommitted, 2));
      this.dispatchEvent(new CustomEvent('action:delete', {
        detail: { committed: this._pendingCommitted ?? '' }
      }));
    }

    // Drain cursor-move queue (DPAD pressed with no candidates showing)
    let cmCode = wasm.mie_pop_cursor_move();
    while (cmCode !== 0) {
      const dir = ['', 'left', 'right', 'up', 'down'][cmCode] ?? '';
      this.dispatchEvent(new CustomEvent('cursor:move', { detail: { dir } }));
      cmCode = wasm.mie_pop_cursor_move();
    }

    // Emit composition update
    const candidates    = this.getCandidates();
    const allCandidates = this.getAllCandidates();
    const pending       = this.getPendingView();
    const modeStr       = this.getModeStr();
    const picker        = this.getPicker();
    this.dispatchEvent(new CustomEvent('composition:update', {
      detail: {
        buffer:       pending.str,          // back-compat (string)
        pending,                             // { str, byteLen, matchedPrefixBytes, style }
        candidates,                          // page-slice (firmware kPageSize)
        allCandidates,                       // full merged list
        selectedAbs:  this.getSelectedAbs(),
        committed:    this._pendingCommitted ?? '',
        mode:         modeStr,
        sel:          this.getPageSel(),
        page:         this.getCurrentPage(),
        pageCount:    this.getPageCount(),
        picker,                              // { active, cols, cellCount, selected, cells }
        wasm:         true,
      }
    }));
  }

  // ── JS event forwarding (Phase 1–3) ─────────────────────────

  _forwardEvents() {
    const forward = (type) => {
      this._jsImpl.addEventListener(type, (e) => {
        this.dispatchEvent(new CustomEvent(type, { detail: e.detail }));
      });
    };
    ['composition:update','composition:commit','cursor:move',
     'action:back','action:menu','action:enter','action:delete',
     'mode:change'
    ].forEach(forward);
  }

  _emit(type, detail) {
    this.dispatchEvent(new CustomEvent(type, { detail }));
  }
}
